In [1]:
import torch 
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt    

In [4]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
tensor = torch.tensor([1 ,2 ,3])
tensor

tensor([1, 2, 3])

In [7]:
nparray = np.array([1, 2, 3])
nparray

array([1, 2, 3])

In [9]:
tensor = torch.tensor([2.0, 3.0], requires_grad=True)
result = tensor * 2
result.sum().backward()  # Calculate gradients
print(tensor.grad)


tensor([2., 2.])


In [14]:
tensor.ndim  , scalar.item() , # not for higher that one elment tensor like tensor.item()

(1, 7)

In [21]:
tensor.shape

torch.Size([2])